import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing import image

print("=== Lab 31: Visualizing Intermediate Activations ===")

# Task 1: Load pretrained VGG16 model
model = VGG16(
    weights="imagenet",
    include_top=True
)

print("\nVGG16 model loaded successfully")

# Create a sample image if no external image is available
sample_img = np.zeros((224, 224, 3), dtype=np.uint8)
sample_img[:, :, 0] = 120
sample_img[50:170, 50:170, 1] = 255
sample_img[80:140, 80:140, 2] = 255

plt.figure(figsize=(4, 4))
plt.imshow(sample_img)
plt.axis("off")
plt.tight_layout()
plt.savefig("sample_input_image.png")
plt.close()

# Load and preprocess image
img_path = "sample_input_image.png"

img = image.load_img(
    img_path,
    target_size=(224, 224)
)

img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = preprocess_input(img_array)

print("\nInput image preprocessed successfully")
print("Input image shape:", img_array.shape)

# Feed image through network
preds = model.predict(img_array, verbose=0)

print("\nPrediction completed")
print("Prediction output shape:", preds.shape)

# Task 2: Extract activations from intermediate convolutional layers
layer_names = [
    layer.name
    for layer in model.layers
]

print("\nModel Layers:")
for name in layer_names[:10]:
    print(name)

# Select convolutional layers for activation visualization
selected_layer_names = [
    "block1_conv1",
    "block1_conv2",
    "block2_conv1",
    "block2_conv2"
]

layer_outputs = [
    model.get_layer(name).output
    for name in selected_layer_names
]

activation_model = Model(
    inputs=model.input,
    outputs=layer_outputs
)

activations = activation_model.predict(
    img_array,
    verbose=0
)

print("\nIntermediate activations extracted successfully")

# Save layer activation information
activation_info = []

for layer_name, activation in zip(selected_layer_names, activations):
    activation_info.append({
        "Layer_Name": layer_name,
        "Activation_Shape": str(activation.shape),
        "Number_of_Feature_Maps": activation.shape[-1]
    })

activation_df = pd.DataFrame(activation_info)
activation_df.to_csv("activation_layer_info.csv", index=False)

# Task 3: Visualize first feature map from each selected layer
plt.figure(figsize=(16, 4))

for i, activation in enumerate(activations):
    plt.subplot(1, len(activations), i + 1)
    plt.imshow(activation[0, :, :, 0], cmap="viridis")
    plt.title(selected_layer_names[i])
    plt.axis("off")

plt.tight_layout()
plt.savefig("selected_layer_activations.png")
plt.close()

# Visualize multiple feature maps from first selected layer
first_activation = activations[0]
num_features = 16

plt.figure(figsize=(10, 10))

for i in range(num_features):
    plt.subplot(4, 4, i + 1)
    plt.imshow(first_activation[0, :, :, i], cmap="viridis")
    plt.title(f"Map {i + 1}")
    plt.axis("off")

plt.tight_layout()
plt.savefig("block1_conv1_feature_maps.png")
plt.close()

# Save report
with open("intermediate_activations_report.txt", "w") as file:
    file.write("Lab 31: Visualizing Intermediate Activations\n\n")
    file.write("Model Used: VGG16 pretrained on ImageNet\n")
    file.write("Input Image: sample_input_image.png\n\n")

    file.write("Selected Layers:\n")
    for name in selected_layer_names:
        file.write(f"- {name}\n")

    file.write("\nInterpretation:\n")
    file.write("Intermediate activations show feature maps generated by convolutional layers.\n")
    file.write("Early layers usually detect edges, colors, and simple textures.\n")
    file.write("Deeper layers combine simple features into more meaningful patterns.\n")
    file.write("Visualizing activations helps understand how CNNs transform image data.\n")

print("\nFiles saved:")
print("sample_input_image.png")
print("activation_layer_info.csv")
print("selected_layer_activations.png")
print("block1_conv1_feature_maps.png")
print("intermediate_activations_report.txt")

print("\nLab completed successfully.")
